server:
   port: 8081
   servlet:
      context-path: /
spring:
   data:
      jdbc:
         initialize-schema: never
   application:
      name: point-sale-web-api
   datasource:
      name: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
         connectionTimeout: 30000
         idleTimeout: 30000
         maxLifetime: 1800000
         maximum-pool-size: 20
         minimum-idle: 2
      password: postgres
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=point_sale
      username: postgres
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      generate-ddl: false
      properties:
         hibernate:
            default_schema: point_sale
            dialect: org.hibernate.dialect.PostgreSQLDialect
            temp:
               use_jdbc_metadata_defaults: false